image: jpetazzo/dind
git:
  path: github.com/johnae/test_ci
script:
  - /etc/init.d/docker start
  - echo "sleeping" && sleep 5
  - ls -lah /var/run/
  - docker -v
  - docker images
  - /etc/init.d/docker stop