image: jpetazzo/dind
env:
  - FOO=BAR
  - DOCKER_HOST=tcp://172.17.42.1:2375
git:
  path: github.com/johnae/test_ci
script:
  - docker -v
  - docker images
  - env
  - docker build -t johnae/test_ci:master .
  - docker run --rm johnae/test_ci:master test_runner
  - docker rmi -f johnae/test_ci:master || true